### ISSUE TITLE
cmip5 land issues

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#197]
When I click model->cmip5->picontrol->land-> I get this:
<img width="835" alt="Screen Shot 2020-11-05 at 3 12 48 PM" src="https://user-images.githubusercontent.com/16332933/98302295-5efbdb80-1f79-11eb-8fa6-520d3d55c854.png">

This page should only contain the `day` subcatalog.

**Comment by bnoushin7** [comment]
@kpegion I guess it should be this way. Because we already had a "land" data catalog named land.html. 
We can not have more than one land.html in the system. I guess we have to come up with a solution, like changing the name of one of them. Maybe I can change the previous name o gridded_land or something else?

**Comment by bnoushin7** [comment]
Done!
