### ISSUE TITLE
List all datasets in catalog by tag

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#41]
Users may want to list all available data by tags or combination of tags.  For example, list all daily precipitation data.  Need example.

**Comment by bnoushin7** [comment]
First, I tried to write a function that returns all datasets based on the tag search. But it is not the best way, because the user needs to first install my package. I worked to develop another way that it only needs to load my function and call the function by tag.
Please find the notebook attached.
