### ISSUE TITLE
Change catalog_dir for datasets to be the local sub catalog

### ISSUE THREAD

**Issue by kpegion** [kpegion/COLA-DATASETS-CATALOG#47]
The catalog_dir listed for each dataset should be the specific sub catalog for that dataset.  For example in:
<img width="1189" alt="Screen Shot 2020-07-20 at 11 29 41 AM" src="https://user-images.githubusercontent.com/16332933/87968274-62785f00-ca7d-11ea-98cc-d20c948f6658.png">

```
catalog_dir https://github.com/kpegion/COLA-DATASETS-CATALOG
```
should be
```
catalog_dir https://kpegion.github.io/COLA-DATASETS-CATALOG/precip
```

**Comment by bnoushin7** [comment]
Do you mean it should match the catalog file name? Because for this one, the catalog file is also precip.yaml.
But we do not have different directories for yaml files. All of them are located in intake-catalogs directory.
If I want to give another example, it would be [this](http://127.0.0.1:4000/COLA-DATASETS-CATALOG/olr.day.mean.nc.html).
Should I change the catalog_dir to "https://kpegion.github.io/COLA-DATASETS-CATALOG/olr.day.mean.nc.html" ? 
Because all of them are located in intake-catalog.
@kpegion

**Comment by kpegion** [comment]
_Should I change the catalog_dir to "https://kpegion.github.io/COLA-DATASETS-CATALOG/olr.day.mean.nc.html" ?_

Yes. This is what I meant.

**Comment by bnoushin7** [comment]
One more quick question. So should it exactly reflect what is inside
"cat = open_catalog("https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/NOAA_INTERP_OLR_daily.yaml")"?

I mean should have it as:
https://raw.githubusercontent.com/kpegion/COLA-DATASETS-CATALOG/gh-pages/intake-catalogs/NOAA_INTERP_OLR_daily.yaml
?
@kpegion

**Comment by kpegion** [comment]
yes, that looks right to me.

**Comment by bnoushin7** [comment]
Done!
